---
sidebar: sidebar 
permalink: about/whats-new.html 
keywords: whats new, enhancements, new features 
summary: A NetApp atualiza regularmente as soluções de automação, as APIs REST do produto e o software relacionado para oferecer novos recursos, melhorias e correções de bugs. 
---
= Novidades da automação NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A NetApp atualiza regularmente as soluções de automação, as APIs REST do produto e o software relacionado para oferecer novos recursos, melhorias e correções de bugs.



== 27 de julho de 2023

.Cloud Volumes ONTAP
O suporte ao Cloud Volumes ONTAP é organizado pelo ambiente de nuvem pública. Uma nova solução é fornecida para o seguinte ambiente de nuvem:

* link:../solutions/cvo-gcp-burst-to-cloud.html["Cloud Volumes ONTAP para Google Cloud - estourar para a nuvem"]




== 04 de junho de 2023

O https://console.netapp.com/automationCatalog["Catálogo de automação do NetApp Console"^] está disponível por meio da interface de usuário da web do Console.  O catálogo de automação fornece acesso a soluções que podem ajudar você com a implantação e integração automatizadas de produtos NetApp .  A documentação dessas soluções é organizada em diversas áreas funcionais ou de produtos, conforme descrito abaixo.

.Amazon FSx for NetApp ONTAP
Duas soluções de gerenciamento do Amazon FSx for NetApp ONTAP são fornecidas da seguinte forma:

* link:../solutions/fsxn-burst-to-cloud.html["Amazon FSx for NetApp ONTAP - Explosão para a nuvem"]
* link:../solutions/fsxn-disaster-recovery.html["Gerenciamento do Amazon FSx for NetApp ONTAP - Recuperação de desastres"]


.Azure NetApp Files
Uma solução está incluída para ajudá-lo a implantar o Oracle com o Azure NetApp Files:

* link:../solutions/anf-oracle.html["Oracle usando Azure NetApp Files"]


.Cloud Volumes ONTAP
O suporte ao Cloud Volumes ONTAP é organizado pelo ambiente de nuvem pública. As soluções iniciais são fornecidas para dois ambientes de nuvem da seguinte forma:

* link:../solutions/cvo-aws-burst-to-cloud.html["Cloud Volumes ONTAP AWS: Explosão na nuvem"]
* link:../solutions/cvo-azure-burst-to-cloud.html["Cloud Volumes ONTAP Azure - Burst para a nuvem"]

