---
sidebar: sidebar 
permalink: solutions/bac-overview.html 
keywords: bluexp automation hub, automation hub, overview, introduction 
summary: O hub de automação do NetApp Console é uma coleção de soluções de automação disponíveis para clientes, parceiros e funcionários da NetApp . O hub possui diversas funcionalidades e benefícios. 
---
= Visão geral do hub de automação do NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O hub de automação do NetApp Console é uma coleção de soluções de automação disponíveis para clientes, parceiros e funcionários da NetApp . O hub de automação possui diversas funcionalidades e benefícios.

Um único local para suas necessidades de automação:: Você pode acessar o https://console.netapp.com/automationHub["Hub de automação do NetApp Console"^] através da interface de usuário web do Console. Isso fornece um local único para os scripts, playbooks e módulos necessários para aprimorar a automação e a operação de seus produtos e serviços NetApp .
As soluções são criadas e testadas pela NetApp:: Todas as soluções de automação e scripts foram criados e testados pela NetApp. Cada solução destina-se a um caso de uso ou solicitação específico do cliente. A maior parte do foco é a integração com os serviços de dados e arquivos do NetApp.
Documentação:: Cada uma das soluções de automação inclui documentação associada para ajudar você a começar.  Embora as soluções sejam acessadas pela interface web do Console, toda a documentação está disponível neste site.  A documentação é organizada com base nos produtos e serviços de nuvem da NetApp .
Base sólida para o futuro:: A NetApp está empenhada em ajudar nossos clientes a aprimorar e simplificar a automação de seus data centers e ambientes de nuvem. Esperamos continuar aprimorando o hub de automação do Console para atender às necessidades dos clientes, às mudanças tecnológicas e à integração contínua de produtos.
Queremos ouvir de você:: A equipe de automação do escritório de experiência do Cliente (CXO) da NetApp gostaria de ouvir de você. Se você tiver algum feedback, problemas ou solicitações de recursos, envie um e-mail para NetApp.com[equipe de automação CXO].

