---
sidebar: sidebar 
permalink: api/astra.html 
keywords: netapp products, product api, rest, rest api, astra, astra control 
summary: O Astra Control é um produto de software da NetApp que fornece gerenciamento de dados com reconhecimento de aplicações de clusters do Kubernetes em vários ambientes. Os dois modelos de implantação compartilham uma API REST comum. Consulte a documentação e os recursos relacionados fornecidos abaixo para dar os primeiros passos com a automação das implantações do Astra. 
---
= Astra Control
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O Astra Control é um produto de software da NetApp que fornece gerenciamento de dados com reconhecimento de aplicações de clusters do Kubernetes em vários ambientes. Os dois modelos de implantação compartilham uma API REST comum. Consulte a documentação e os recursos relacionados fornecidos abaixo para começar a automação de suas implantações Astra usando a API REST Astra Control.

.API REST do Astra Control
Você pode usar a API REST para automatizar a administração das suas implantações do Astra Control Service e do Astra Control Center.

* https://docs.netapp.com/us-en/astra-automation/["Documentação do Astra Control Automation"^]


.Família Astra
A documentação da família Astra inclui tudo o que você precisa para instalar e administrar o Astra e os softwares relacionados.

* https://docs.netapp.com/us-en/astra-family/["Documentação do Astra"^]

